version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
      - REACT_APP_GUARDIAN_API_KEY=${REACT_APP_GUARDIAN_API_KEY}
      - REACT_APP_NYT_API_KEY=${REACT_APP_NYT_API_KEY}

